export const provinces = [
  {
    province: "Cuanza Sul",
    municipalties: [
      "Amboim",
      "Cassongue",
      "Cela",
      "Conda",
      "Ebo",
      "Libolo",
      "Mussende",
      "Porto Amboim",
      "Quibala",
      "Quilenda",
      "Seles",
      "Sumbe",
    ],
  },
  {
    province: "Bengo",
    municipalties: [
      "Ambriz",
      "Bula Atumba",
      "Dande",
      "Dembos",
      "Nambuangongo",
      "Pango Aluquém",
    ],
  },
  {
    province: "Benguela",
    municipalties: [
      "Balombo",
      "Baía Farta",
      "Benguela",
      "Bocoio",
      "Caimbambo",
      "Catumbela",
      "Chongorói",
      "Cubal",
      "Ganda",
      "Lobito",
    ],
  },
  {
    province: "Bie",
    municipalties: [
      "Andulo",
      "Camacupa",
      "Catabola",
      "Chinguar",
      "Chitembo",
      "Cuemba",
      "Cunhinga",
      "Cuíto",
      "Nharea",
    ],
  },

  {
    province: "Cabinda",
    municipalties: ["Belize", "Buco-Zau", "Cabinda", "Cacongo"],
  },
  {
    province: "Cuando Cubango",
    municipalties: [
      "Calai",
      "Cuangar",
      "Cuchi",
      "Cuito Cuanavale",
      "Dirico",
      "Mavinga",
      "Menongue",
      "Nancova",
      "Rivungo",
    ],
  },

  {
    province: "Cuanza Norte",
    municipalties: [
      "Ambaca",
      "Banga",
      "Bolongongo",
      "Cambambe",
      "Cazengo",
      "Golungo Alto",
      "Gonguembo",
      "Lucala",
      "Quiculungo",
      "Samba Caju",
    ],
  },
];
